#!/bin/sh

. /lib/functions.sh

case "$ACTION" in
pressed)
	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -gt 3 ]
	then
#		echo "FACTORY RESET" > /dev/console
#		jffs2reset -y && reboot &
		echo "RESET CONFIG & REBOOT" > /dev/console
		uci set network.lan.ipaddr=192.168.100.1
		uci set network.lan.netmask=255.255.255.0
		uci set network.lan.gateway=0.0.0.0
		uci commit
		/etc/init.d/dnsmasq enable
		echo '{"username":"admin","password":""}' >/root/login.conf
		sync
		reboot
	fi
;;
esac

return 0
